class Lexicon:
    welcome = "Добро пожаловать в Персональный помощник!"

    no_such_action = 'Нет такой команды'

    choose_action = (
        "Выберите действие:\n"
        "1. Управление заметками\n"
        "2. Управление задачами\n"
        "3. Управление контактами\n"
        "4. Управление финансовыми записями\n"
        "5. Калькулятор\n"
        "6. Выход"
    )

    # Заметки
    add_note_success = "Заметка успешно добавлена и сохранена."
    edit_note_success = "Заметка успешно отредактирована и изменения сохранены."
    delete_note_success = "Заметка успешно удалена ."
    export_notes_success = "Заметки успешно экспортированы в notes_export.csv."
    import_notes_success = "Заметки успешно импортированы из указанного файла."
    choose_note_action = "Выберите действие:\n1. Добавить заметку\n2. Редактировать заметку\n3. Удалить заметку\n4. Просмотреть заметки\n"
    enter_note_title = "Введите заголовок заметки: "
    enter_note_content = "Введите содержание заметки: "
    enter_note_timestamp = "Введите дату заметки: "
    enter_note_id = "Введите ID заметки для редактирования: "
    enter_note_edit_title = "Введите новый заголовок заметки: "
    enter_note_edit_content = "Введите новое содержание заметки: "
    enter_note_id_delete = "Введите ID заметки для удаления: "

    add_task_success = "Задача успешно добавлена и сохранена в tasks.json."
    mark_task_completed = "Задача отмечена как выполненная."
    choose_task_action = "Выберите действие:\n1. Добавить задачу\n2. Отметить задачу как выполненную\n3. Просмотреть задачи\n4. Редактировать задачу\n5. Удалить задачу\n"
    enter_task_title = "Введите название задачи: "
    enter_task_description = "Введите описание задачи: "
    choose_task_priority = "Выберите приоритет (Высокий/Средний/Низкий): "
    enter_task_due_date = "Введите срок выполнения (в формате ДД-ММ-ГГГГ): "
    enter_task_id = "Введите ID задачи для отметки как выполненной: "
    enter_task_id_edit = "Введите ID задачи для редактирования: "
    enter_task_id_delete = "Введите ID задачи для удаления: "
    edit_task_success = "задача успешно отредактирована и изменения сохранены."
    delete_task_success = "задача успешно удалена."

    add_contact_success = "Контакт успешно добавлен и сохранен."
    edit_contact_success = "Контакт успешно отредактирован."
    delete_contact_success = "Контакт успешно удален."
    choose_contact_action = "Выберите действие:\n1. Добавить контакт\n2. Редактировать контакт\n3. Удалить контакт\n4. Искать контакт по имеени\n5. искать контакт по номеру"
    enter_contact_name = "Введите имя контакта: "
    enter_contact_phone = "Введите номер телефона контакта: "
    enter_contact_email = "Введите email контакта: "
    enter_contact_id = "Введите ID контакта для редактирования: "
    enter_contact_id_delete = "Введите ID контакта для удаления: "

    add_record_success = "Финансовая запись успешно добавлена."
    choose_record_action = "Выберите действие:\n1. Добавить запись\n2. Просмотреть записи\n3. Сформировать отчет\n4. Импортировать записи\n5. Экспортировать записи\n"
    enter_record_amount = "Введите сумму записи: "
    enter_record_category = "Введите категорию записи: "
    enter_record_date = "Введите дату записи (в формате ДД-ММ-ГГГГ): "
    enter_record_description = "Введите описание задачи"
    enter_record_filter_category = "Введите категорию для фильтрации: "
    enter_record_filter_date = "Введите дату для фильтрации (в формате ДД-ММ-ГГГГ): "
    enter_report_start_date = "Введите начальную дату для отчета (в формате ДД-ММ-ГГГГ): "
    enter_report_end_date = "Введите конечную дату для отчета (в формате ДД-ММ-ГГГГ): "
    total_balance_message = "Общий баланс: {}"
    group_by_category_message = "Записи сгруппированы по категориям."
    export_financial_records_success = "Финансовые записи успешно экспортированы в finance_export.csv."
    import_financial_records_success = "Финансовые записи успешно импортированы из указанного файла"

    calc_enter_operation = "Введите название операции"
    calc_enter_first_arg = "Введите первый аргумент"
    calc_enter_second_arg = "Введите второй аргумент"
    incorrect_command = 'Incorrect command'