class RecordManager:
    def __init__(self):
        ...

    def add_record(self):
        ...

    def get_records(self, filter_by_category: bool = False, filter_by_date: bool=False):
        ...

    def form_report(self, date):
        ...

    def load_from_csv(self):
        ...

    def total_balance(self):
        ...

    def group_by_category(self):
        ...